### ISSUE TITLE
multiple errors

### ISSUE THREAD

**Issue by Doriginal** [nadirlc/MP3-Management#1]
hi,

Thank you for your code.
when I scan a folder, I have multiple errors.

![capture](https://cloud.githubusercontent.com/assets/1387182/5605821/908bebc6-9411-11e4-8daf-50b532b7f56c.PNG)

At the end of the page it looks like a piece of code appears

![capture2](https://cloud.githubusercontent.com/assets/1387182/5605826/bed13f22-9411-11e4-942c-3ba139b9d04b.PNG)

Thank's for your help

MAJ1: I fixed some from errors with the latest getid3 (http://sourceforge.net/projects/getid3/files/getID3%28%29%201.x/1.9.9/)

MAJ2: Corrected errors in my log folder and Album_art folder.
           It remains this:

![capture](https://cloud.githubusercontent.com/assets/1387182/5605957/4a4cc12e-9418-11e4-805a-7e63b153f095.PNG)

**Comment by nadirlc** [comment]
Hi,

Thanks for your feedback. The file clip_files.php did not have the <?php tag at the start. I added it. It should fix the error that is displaying Fatal error and also the code displayed above the error box. 

I also fixed the Notice error and updated the getid3 library to latest version. Please make a fresh checkout of all the files and also empty the database tables used by the script.

Thanks,
Nadir Latif

**Comment by Doriginal** [comment]
it's work, thank you.
